### PR TITLE
Reverts condition effectuating rate limit to working order

### PR DESCRIPTION
**Pull request by bravo-kernel**

### CODE REVIEW

**Comment by ADmad** [comment]
Change looks good, could you just add test please.

**Comment by bravo-kernel** [comment]
I'm actually doing that right now but am having a hard time figuring out the best approach. Setting 'rate' to 2 and then sending requests seems most logical but I can't change the protected config (yet).

Pointers would be appreciated.

**Comment by bravo-kernel** [comment]
Something got squashed here, will need to fix

**Comment by bravo-kernel** [comment]
Closing this in favor of a new PR

**Pull request closed without merging**
